//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _SIC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderId { get; set; }
        public string ProductName { get; set; }
        public string Brand { get; set; }
        public string Specification { get; set; }
        public string Warehouse { get; set; }
        public string Room { get; set; }
        public string Aisle { get; set; }
        public string ProductType { get; set; }
        public string Shelf { get; set; }
        public string Quantity { get; set; }
        public string Currency { get; set; }
        public string Price { get; set; }
        public int CustomerCustomerId { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
